version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - .jenkins/home:/var/jenkins_home
    ports:
      - 8081:8080
    privileged: true
    user: root
